### PR TITLE
skip MONGO_URI in config env if not enabled

### PR DESCRIPTION
**Pull request by pnancarrow**
I am using a hosted mongodb and am hitting this issue when setting mongodb: enabled: false

### CODE REVIEW

**Comment by pnancarrow** [comment]
hey @hofq, one more I could use an eye on 😄

**Comment by hofq** [comment]
i will check tomorrow

**Comment by hofq** [comment]
Thx for the PR :) @pnancarrow

**Comment by pnancarrow** [comment]
Thanks for the quick review @hofq !

**Pull request merged**
